version: '3.8'
services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    restart: unless-stopped
    networks:
      br0:
        ipv4_address: 192.168.0.5
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /mnt/zfs/appdata/homeassistant:/config
networks:
  br0:
    external: true
