services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    ports:
      - 32400:32400
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - VERSION=docker
      - PLEX_CLAIM="${PLEX_CLAIM}"
    volumes:
      - /mnt/zfs/appdata/plex:/config
      - /mnt/zfs/scrbl/movies:/movies
      - /mnt/zfs/scrbl/series:/tv
      - /mnt/zfs/scrbl/anime:/anime
      - /mnt/zfs/scrbl/screencasts:/screencasts
