# See https://go.dev/dl
- name: Determine go release suffix
  set_fact:
    go_release_suffix: >-
      {{
      {
        'aarch64': 'linux-arm64'
      }.get(ansible_architecture, 'linux-amd64')
      }}
- name: Set up go {{ go_version }}
  block:
    - name: Ensure /etc/zprofile exists
      ansible.builtin.file:
        path: /etc/zprofile
        state: touch
    - name: Download go {{ go_version }}
      ansible.builtin.get_url:
        url: "https://golang.org/dl/go{{ go_version }}.{{ go_release_suffix }}.tar.gz"
        dest: /tmp/go{{ go_version }}.{{ go_release_suffix }}.tar.gz
      register: go_download
    - name: Install go {{ go_version }}
      ansible.builtin.unarchive:
        src: "{{ go_download.dest }}"
        dest: /usr/local
    - name: Set up go environment
      block:
        - name: Add go to /etc/profile
          ansible.builtin.lineinfile:
            path: /etc/profile
            line: "export PATH=$PATH:/usr/local/go/bin"
        - name: Add go to /etc/zprofile
          ansible.builtin.lineinfile:
            path: /etc/zprofile
            line: "export PATH=$PATH:/usr/local/go/bin"
  always:
    - name: Remove go download
      ansible.builtin.file:
        path: "{{ go_download.dest }}"
        state: absent

