- name: Install go {{ go_version }}
  tags:
    - personal
  ansible.builtin.shell: |
    curl -fsSL https://golang.org/dl/go{{ go_version }}.linux-amd64.tar.gz -o go{{ go_version }}.linux-amd64.tar.gz
    sudo tar -C /usr/local -xzf go{{ go_version }}.linux-amd64.tar.gz
    rm go{{ go_version }}.linux-amd64.tar.gz
  become: true
