---
- name: Create the source directory
  ansible.builtin.file:
    path: /home/{{ username }}/source
    state: directory
  become: true
  become_method: ansible.builtin.sudo
  become_user: "{{ username }}"
  become_flags: '-i'

- name: Create the .local/bin directory
  ansible.builtin.file:
    path: /home/{{ username }}/.local/bin
    state: directory
  become: true
  become_method: ansible.builtin.sudo
  become_user: "{{ username }}"
  become_flags: '-i'

- name: Install docker
  ansible.builtin.import_tasks: docker.yml

- name: Install go {{ go_version }}
  ansible.builtin.import_tasks: go.yml

- name: Install fzf {{ fzf_version }}
  import_tasks: fzf.yml

- name: Install starhip {{ starship_version }}
  ansible.builtin.import_tasks: starship.yml

- name: Set up dotfiles
  ansible.builtin.import_tasks: dotfiles.yml

- name: Install neovim {{ neovim_version }}
  ansible.builtin.import_tasks: neovim.yml

- name: Install deno {{ deno_version }}
  ansible.builtin.import_tasks: deno.yml

- name: Install node {{ node_version }}
  ansible.builtin.import_tasks: nodejs.yml

- name: Install python {{ python_version }}
  ansible.builtin.import_tasks: python.yml
