---
- name: Install neovim build dependencies
  package:
    name:
      - build-essential
      - cmake
      - gettext
      - ninja-build
    state: latest

- name: Clone neovim {{ neovim_version }}
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: /home/{{ username }}/source/neovim
    single_branch: yes
    version: "v{{ neovim_version }}"
  become: true
  become_method: ansible.builtin.sudo
  become_user: "{{ username }}"

- name: Build neovim {{ neovim_version }}
  make:
    chdir: /home/{{ username }}/source/neovim
    params:
      CMAKE_BUILD_TYPE: "Release"
  become: true

- name: Install neovim
  make:
    chdir: /home/{{ username }}/source/neovim
    target: install
  become: true
