- name: Set up nodejs {{ node_version }}
  become: true
  become_method: ansible.builtin.sudo
  become_user: "{{ username }}"
  become_flags: '-i'
  block:
    - name: Install fnm
      ansible.builtin.shell: |
        curl -fsSL https://fnm.vercel.app/install | bash

    - name: Install node {{ node_version }}
      ansible.builtin.shell: |
        source .zshrc && fnm install {{ node_version }}
      args:
        chdir: /home/{{ username }}
        executable: "{{ lookup('ansible.builtin.pipe', 'which zsh') }}"

    - name: Set default node version to {{ node_version }}
      ansible.builtin.shell: |
        source .zshrc && fnm default {{ node_version }}
      args:
        chdir: /home/{{ username }}
        executable: "{{ lookup('ansible.builtin.pipe', 'which zsh') }}"
