- name: Update packages
  tags:
  - essential
  apt:
    update_cache: yes
    upgrade: yes
- name: Install system packages
  tags:
  - essential
  package:
    name:
    - sudo
    - build-essential
    - gcc
    - ninja-build
    - gettext
    - cmake
    - zlib1g
    - zlib1g-dev
    - libssl-dev
    - libbz2-dev
    - libsqlite3-dev
    - unzip
    - ca-certificates
    - curl
    - git
    - vim
    - neofetch
    - htop
    - tmux
    - stow
    - zsh
    - ripgrep
    - fzf
    - jq
    state: latest

- name: Disable SSH password auth
  tags:
  - essential
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#PasswordAuthentication yes"
    line: "PasswordAuthentication no"
  register: sshd_config

- name: Enable passwordless sudo for "{{ username }}"
  tags:
  - essential
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: Add the docker repository
  tags:
  - essential
  ansible.builtin.shell: |
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
    chmod a+r /etc/apt/keyrings/docker.asc
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
      $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
      tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Update package list
  tags:
  - essential
  apt:
    update_cache: yes

- name: Install docker
  tags:
  - essential
  package:
    name: docker

- name: Change shell to zsh
  tags:
  - personal
  ansible.builtin.shell: |
    chsh -s $(which zsh) {{ username }}

- name: Insall ohmyzsh
  tags:
  - personal
  ansible.builtin.shell: |
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  become: true
  become_method: sudo
  become_user: "{{ username }}"
  become_flags: '-i'

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  become: true
  become_method: sudo
  become_user: "{{ username }}"
  become_flags: '-i'

- name: Clone dotfiles
  ansible.builtin.git:
    repo: 'https://github.com/attadanta/dotfiles.git'
    dest: ~/.dotfiles
  become: true
  become_method: sudo
  become_user: "{{ username }}"
  become_flags: '-i'

- name: Stow dotfiles
  ansible.builtin.shell: |
    stow --adopt .
  args:
    chdir: /home/{{ username }}/.dotfiles
  become: true
  become_method: sudo
  become_user: "{{ username }}"
  become_flags: '-i'

- name: Install pyenv
  tags:
  - personal
  ansible.builtin.shell: |
    curl https://pyenv.run | bash
  become: true
  become_method: sudo
  become_user: "{{ username }}"
  become_flags: '-i'

- name: Install fnm
  tags:
  - personal
  ansible.builtin.shell: |
    curl -fsSL https://fnm.vercel.app/install | bash
  args:
    executable: /bin/bash
  become: true
  become_method: sudo
  become_user: "{{ username }}"
  become_flags: '-i'

- name: Install node
  tags:
  - personal
  ansible.builtin.shell: |
    source .zshrc
    fnm install --lts
  args:
    executable: /bin/bash
    chdir: /home/{{ username }}
  become: true
  become_method: sudo
  become_user: "{{ username }}"
  become_flags: '-i'

