- name: Install GPG
  tags:
    - essential
  package:
    name:
      - gpg
    state: latest

- name: Add Docker GPG apt Key
  tags:
    - essential
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  tags:
    - essential
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu noble stable
    state: present

- name: Install system packages
  tags:
    - essential
  package:
    name:
      - sudo
      - build-essential
      - gcc
      - ninja-build
      - gettext
      - cmake
      - zlib1g
      - zlib1g-dev
      - libssl-dev
      - libbz2-dev
      - libsqlite3-dev
      - unzip
      - ca-certificates
      - curl
      - git
      - vim
      - neofetch
      - htop
      - tmux
      - stow
      - zsh
      - ripgrep
      - fzf
      - jq
      - docker-ce
    state: latest

- name: Disable SSH password auth
  tags:
    - essential
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#PasswordAuthentication yes"
    line: "PasswordAuthentication no"
  register: sshd_config

- name: Enable passwordless sudo for "{{ username }}"
  tags:
    - essential
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: Change shell to zsh
  tags:
    - essential
  ansible.builtin.shell: |
    chsh -s $(which zsh) {{ username }}

- name: Insall ohmyzsh
  tags:
    - personal
  ansible.builtin.shell: |
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
    mv ~/.zshrc ~/.zshrc.orig
  become: true
  become_method: ansible.builtin.sudo
  become_user: "{{ username }}"
  become_flags: '-i'

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  become: true
  become_method: ansible.builtin.sudo
  become_user: "{{ username }}"
  become_flags: '-i'

- name: Create the source directory
  tags:
    - personal
  ansible.builtin.file:
    path: /home/{{ username }}/source
    state: directory
  become: true
  become_method: ansible.builtin.sudo
  become_user: "{{ username }}"
  become_flags: '-i'

- name: Clone dotfiles
  ansible.builtin.git:
    repo: 'https://github.com/attadanta/dotfiles.git'
    dest: ~/.dotfiles
  become: true
  become_method: ansible.builtin.sudo
  become_user: "{{ username }}"
  become_flags: '-i'

- name: Stow dotfiles
  ansible.builtin.shell: |
    stow --adopt .
  args:
    chdir: /home/{{ username }}/.dotfiles
  become: true
  become_method: ansible.builtin.sudo
  become_user: "{{ username }}"

- name: Clone neovim
  tags:
    - personal
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: /home/{{ username }}/source/neovim
    single_branch: yes
    version: v0.10.4
  become: true
  become_method: ansible.builtin.sudo
  become_user: "{{ username }}"

- name: Build neovim
  tags:
    - personal
  make:
    chdir: /home/{{ username }}/source/neovim
    params:
      CMAKE_BUILD_TYPE: "Release"
  become: true

- name: Install neovim
  tags:
    - personal
  make:
    chdir: /home/{{ username }}/source/neovim
    target: install
  become: true

- name: Install pyenv
  tags:
    - personal
  ansible.builtin.shell: |
    curl https://pyenv.run | bash
  become: true
  become_method: ansible.builtin.sudo
  become_user: "{{ username }}"
  become_flags: '-i'

- name: Install fnm
  tags:
    - personal
  ansible.builtin.shell: |
    curl -fsSL https://fnm.vercel.app/install | bash
  become: true
  become_method: ansible.builtin.sudo
  become_user: "{{ username }}"
  become_flags: '-i'

- name: Install node
  tags:
    - personal
  ansible.builtin.shell: |
    source .zshrc && fnm install --lts
  args:
    chdir: /home/{{ username }}
    executable: "{{ lookup('ansible.builtin.pipe', 'which zsh') }}"
  become: true
  become_method: ansible.builtin.sudo
  become_user: "{{ username }}"
  become_flags: '-i'
