- name: Update packages
  apt:
    update_cache: yes
    upgrade: yes

- name: Install system packages
  package:
    name:
    - build-essential
    - gcc
    - ninja-build
    - gettext
    - cmake
    - zlib1g
    - zlib1g-dev
    - libssl-dev
    - libbz2-dev
    - libsqlite3-dev
    - unzip
    - ca-certificates
    - curl
    - git
    - vim
    - neofetch
    - htop
    - tmux
    - stow
    - zsh
    state: latest

- name: Disable SSH password auth
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#PasswordAuthentication yes"
    line: "PasswordAuthentication no"
  register: sshd_config

- name: Enable passwordless sudo for "{{ ansible_user }}"
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: Add the docker repository
  ansible.builtin.shell: |
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
    chmod a+r /etc/apt/keyrings/docker.asc
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
      $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
      tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Update package list
  apt:
    update_cache: yes

- name: Install docker
  package:
    name: docker
