- name: Install key
  ansible.builtin.shell: |
    curl https://pyenv.run | bash
    echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
    echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
    echo 'eval "$(pyenv init -)"' >> ~/.bashrc

- name: Install pyenv
  ansible.builtin.shell: |
    curl https://pyenv.run | bash
    echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
    echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
    echo 'eval "$(pyenv init -)"' >> ~/.bashrc

- name: Install fnm
  ansible.builtin.shell: |
    curl -fsSL https://fnm.vercel.app/install | bash

- name: Build and install python
  ansible.builtin.shell: |
    $HOME/.pyenv/bin/pyenv install 3.12:latest
  args:
    executable: /bin/bash

- name: Install node
  ansible.builtin.shell: |
    $HOME/.fnm/bin/fnm install --lts
  args:
    executable: /bin/bash
