version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    hostname: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8085:8085 # qbittorrent
      - 5005:5005 # Overseerr
      - 9696:9696 # Prowlarr
      - 8686:8686 # Lidarr
      - 8787:8787 # Readarr
      - 6767:6767 # Bazarr
    volumes:
      - /mnt/zfs/appdata/gluetun:/gluetun
    environment:
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/nordvpn.md#obtain-your-wireguard-private-key
      - TZ=${TZ}
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - SERVER_CITIES=Amsterdam
      - UPDATER_PERIOD=24h

  qbittorrent:
    image: ghcr.io/hotio/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=${TZ}
      - WEBUI_PORTS="8085/tcp,8085/udp"
    volumes:
      - /mnt/zfs/appdata/qbittorrent:/config
      - /mnt/zfs/data/torrents:/data
    depends_on:
      - gluetun

  overseerr:
    image: ghcr.io/hotio/overseerr:latest
    container_name: overseerr
    restart: unless-stopped
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=${TZ}
    volumes:
      - /mnt/zfs/appdata/overseerr:/config
    depends_on:
      - gluetun

  prowlarr:
    image: ghcr.io/hotio/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - /mnt/zfs/appdata/prowlarr:/config
    depends_on:
      - gluetun

  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr:latest
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=${TZ}
      - WEBUI_PORTS=6767/tcp,6767/udp
    volumes:
      - /mnt/zfs/appdata/bazarr:/config
      - /mnt/zfs/data/media/subtitles:/data
    depends_on:
      - gluetun

  lidarr:
    image: ghcr.io/hotio/lidarr:latest
    container_name: lidarr
    restart: unless-stopped
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=${TZ}
    volumes:
      - /mnt/zfs/appdata/lidarr:/config
      - /mnt/zfs/data/media/music:/data
    depends_on:
      - gluetun

  readarr:
    image: ghcr.io/hotio/readarr:latest
    container_name: readarr
    restart: unless-stopped
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=${TZ}
    volumes:
      - /mnt/zfs/appdata/readarr:/config
      - /mnt/zfs/data/media/books:/data
    depends_on:
      - gluetun
