services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptimekuma
    restart: unless-stopped
    volumes:
      - /mnt/zfs/appdata/uptime-kuma:/app/data
    ports:
      - 3001:3001
