name: Build and Publish Docker Image

on:
  push:
    branches: [ main ]
    paths:
      - 'ansible/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'ansible/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: ansible

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}-ansible
          tags: |
            type=sha,format=short
            type=ref,event=branch
            latest

      - name: Build initiation image
        uses: docker/build-push-action@v5
        with:
          context: ansible
          push: ${{ github.event_name != 'pull_request' }}
          target: build
          tags: ghcr.io/${{ github.repository }}-ansible:devnode-init
          labels: ${{ steps.meta.outputs.labels }}

      - name: Run ansible playbook
        run: docker run --rm ghcr.io/${{ github.repository }}-ansible:devnode-init /bin/bash -c "ansible-playbook -vvv -i hosts --limit localhost site.yml"

      - name: Build and push ready image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          target: run
          tags: ghcr.io/${{ github.repository }}-ansible:devnode
          labels: ${{ steps.meta.outputs.labels }}
