services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - DUPLICATI__WEBSERVICE_PASSWORD=${WEBSERVICE_PASSWORD}
      - SETTINGS_ENCRYPTION_KEY=${SETTINGS_ENCRYPTION_KEY}
    volumes:
      - /mnt/zfs/appdata/duplicati:/config
      - /mnt/zfs/appdata/duplicati-backups:/backups
      - /mnt/zfs:/source
    ports:
      - 8200:8200
